name: GitHub Metrics
...
- name: Generate GitHub Metrics
  uses: lowlighter/metrics@latest
  with:
    token: ${{ secrets.METRICS_TOKEN }}
    user: VaibhavKumar2005
    ...
    output: github-metrics.svg
...
- name: Commit and Push Metrics SVG
  run: |
    git add github-metrics.svg
    git commit -m "Update GitHub Metrics"
    git push
