name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Daily update
  workflow_dispatch: # Manual trigger
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: VaibhavKumar2005
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          # Theming to match your 'Venom' aesthetic
          config_theme: tokyonight 
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
